config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nurses
  root "nurses#welcome"
  resources :jobs
  resources :profiles
  resources :invoices

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  def self.search(search)
    Job.where("practice like :value or location like:value or jobcode like:value
    or distance like:value or rate like:value", value:"%#{search}%")
  end
end

app/models/nurse.rb
class Nurse < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    has_attached_file :image, :styles => { :medium => "300x300>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index

  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
    if params[:search]
      @jobs = Job.search(params[:search])
    else
      @jobs = Job.all
    end
  end
end

app/controllers/nurses_controller.rb
class NursesController < ApplicationController
  def index

  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/nurses_helper.rb
module NursesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/invoices/index.html.erb
<div class="row">
<div class="col-md-16 clearfix">
<div class="panel-group">

    <div class="panel panel-default with-nav-tabs no-padding">
      <div class="panel-heading "><b>Billing</b></div>
       <div class="panel-body ">

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">All Invoices</a></li>
    <li><a data-toggle="tab" href="#menu1">Paid Invoices</a></li>
    <li><a data-toggle="tab" href="#menu2">Pending Payments</a></li>
  </ul>

          <div class="tab-content">

                <div id="home" class="jobs_body tab-pane fade in active">
                        <table class="table table-bordered table-hover">
                          <thead>
                            <tr>
                              <th>Date</th>
                              <th>Practice</th>
                              <th>Location</th>
                             </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>
                            <tr>
                              <td>02/03/2016</td>
                              <td><a href="http://www.esht.nhs.uk/">East Sussex NHS trust</td>
                              <td>Eastbourne</td>
                              </tr>
                             <tr>
                              <td>07/02/2016</td>
                              <td>Bexley Care Trust</td>
                              <td>Bexley</td>
                              </tr>
                              <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>
                            <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>
                            <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>

                          </tbody>
                        </table>
                  </div>

                <div id="menu1" class="jobs_body tab-pane">
                <table class="table table-bordered table-hover">
                          <thead>
                            <tr>
                              <th>Date</th>
                              <th>Practice</th>
                              <th>Location</th>
                             </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>
                            <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>
                          </tbody>
                        </table>
                </div>

                <div id="menu2" class="jobs_body tab-pane">
                <table class="table table-bordered table-hover">
                          <thead>
                            <tr>
                              <th>Date</th>
                              <th>Practice</th>
                              <th>Location</th>
                             </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td>02/03/2016</td>
                              <td><a href="http://www.esht.nhs.uk/">East Sussex NHS trust</td>
                              <td>Eastbourne</td>
                            </tr>
                            <tr>
                              <td>07/02/2016</td>
                              <td>Bexley Care Trust</td>
                              <td>Bexley</td>
                            </tr>
                            <tr>
                              <td>31/12/2015</td>
                              <td><a href="http://www.kentcht.nhs.uk/home/">Kent NHS trust</td>
                              <td>Tunbridge Wells</td>
                            </tr>

                          </tbody>
                        </table>
                </div>


          </div>

</div>
</div>
</div>
</div>
</div>

app/views/jobs/index.html.erb
<div class="row">
<div class="col-md-12 clearfix">
  <div class="panel-group">
    <div class="panel panel-default no-padding ">
      <div class="panel-heading"><b>Job Listing</b></div>
      <div class="panel-body">
      <form class="form-inline" role="form">
      <div class="form-group no-padding col-md-2">
         <label for="sel1">Within</label>
          <select class="form-control">
            <option>10 Miles</option>
            <option>20 Miles</option>
            <option>30 Miles</option>
            <option>40 Miles</option>
         </select>
       </div>
        <div class="form-group">
        <label for="">of</label>
        <input type="textfield" class="form-control" id="pwd" placeholder="TN12 6BJ">
        </div>
       <div class="form-group">
        <label for="">from&nbsp;</label>
        <input type="text" class="datepicker"  placeholder="DD-MM-YYYY">
        </div>
        <div class="form-group">
        <label for="">&nbsp;&nbsp;to</label>
        <input type="text" class="datepicker" placeholder="DD-MM-YYYY">
        </div>
        <div class="col-sm-3 pull-right">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
        </div>
    </div>
    </div>
  </div>
</div>
</div>
<div class="col-md-16 jobs_body">
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Job Code</th>
      <th>Practice</th>
      <th>Location</th>
      <th>Time</th>
      <th>Distance</th>
      <th>Rate</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |j| %>
    <tr>
      <td><%= j.jobcode %></td>
      <td><%= j.practice %></td>
      <td><%= j.location %> </td>
      <td><%= j.time %></td>
      <td><%= j.distance %></td>
      <td><%= j.rate %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html></html>
<head>
  <title>DirectShift</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "DirectShift", root_path %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Profile",  nurses_path %>
          </li>
          <li>
            <%= link_to "Invoice",  invoices_path %>
          </li>
          <li>
            <%= link_to "Find Jobs", jobs_path %>
          </li>
          <li>
            <%= link_to "Account" , edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>

app/views/nurses/index.html.erb
<div class="row">
<div class="col-md-15 clearfix">
<div class="panel-group">
    <div class="panel panel-default no-padding">
    <div class="panel-heading "><b>Profile</b></div>
           <div class="panel-body">
               <div class="profile-panel-picture panel panel-default pull-left">
                  <h5 class="profile-panel-picture photo"><b>Photo</b></h5>
                   <div class="panel-body"></div>
                </div>
               <div class="experiance-panel panel panel-default">
                    <h5><b>Experiance</b></h5>
                    <div class="panel-body"></div>
                </div>
                <div class="certification-panel panel panel-default">
                   <h5><b>Certification</b></h5>
                    <div class="panel-body"></div>
                </div>
                <div class="education-panel panel panel-default">
                   <h5><b>Education</b></h5>
                    <div class="panel-body"></div>
                </div>
            </div>
     </div>
</div>
</div>
</div>

app/views/nurses/test.html.erb
<hr class="vertical"/>
<div class="row">
<div class="col-md-12 clearfix">
  <div class="panel-group">

    <div class="panel panel-default no-padding ">
      <div class="panel-heading "><b>My Profile</b></div>
       <div class="panel-body panel-height">
       </div>
    </div>
  </div>
</div>
</div>

app/views/nurses/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="/assets/welcome.scss">
</head>
<body>

</body>
</html>

app/views/profiles/index.html.erb
<hr class="vertical"/>
<div class="row">
<div class="col-md-12 clearfix">
  <div class="panel-group">

    <div class="panel panel-default no-padding ">
      <div class="panel-heading "><b>Your Profile / Upload Photo</b></div>
       <div class="panel-body panel-height">
       </div>
    </div>
  </div>
</div>
</div>